### ISSUE TITLE
Angular and Capacitor, scanWithCamera undefined.

### ISSUE THREAD

**Issue by svendjanis** [blinkcard/blinkcard-capacitor#2]
Uncaught (in promise): TypeError: Cannot read property 'scanWithCamera' of undefined TypeError: Cannot read property 'scanWithCamera' of undefined

Cap Version: '3.0.1'

```
  async scan() {

    // Initialize plugin
    const plugin = new BlinkCard.BlinkCardPlugin();

    // Initialize wanted recognizer
    const blinkCardRecognizer = new BlinkCard.BlinkCardRecognizer();
    blinkCardRecognizer.returnFullDocumentImage = true

    // Initialize license
    const licenseKeys: BlinkCard.License = {
      ios: '',
      android: '',
      showTrialLicenseWarning: true
    };

    // Perform scan and gather results
    const scanningResults = await plugin.scanWithCamera(
      new BlinkCard.BlinkCardOverlaySettings(),
      new BlinkCard.RecognizerCollection([blinkCardRecognizer]),
      licenseKeys);
  }

```
  
I have tried this on the new project, cant figure out what is the issue. I would appreciate any help.

**Comment by TCvetkovic** [comment]
Hi Sven,

Thank you for waiting for our response. 

This issue looks like something went wrong with plugin initialization.

Can you check do you have the same issue with our sample?
If our sample is working, can you create some minimal sample app where this issue is possible to reproduce so we could take a look?

Thank you.

**Comment by svendjanis** [comment]
Hi Tomislav,

Thank you for your fast response.
Just tried the sample app, it worked. I will try to implement it into my app now.
